### ISSUE TITLE
实验结果的分类准确度

### ISSUE THREAD

**Issue by gotogotogo** [hbyYoyo/EmotionRecognition_2Dcnn-lstm#1]
可以问一下您的实验结果的准确度是多少吗，万分感谢

**Comment by Hbbbbbby** [comment]
这个模型我训练的时候VAL_ACC一般在%75、%76左右（最好的时候超过80），然后测试的时候ACC是%77左右。您可以试着跑一下，我用1050TI几分钟就可以跑下来了。

> 可以问一下您的实验结果的准确度是多少吗，万分感谢

**Comment by gotogotogo** [comment]
谢谢~

**Comment by Hbbbbbby** [comment]
> 谢谢~

感谢您的浏览。^ _ ^
